

data_shape: [1]
# [EightGaussians2D, Moon, Gaussian]
data:
  source: 
    type:
      datasets.distribution.Gaussian
    args:
      data_shape: ${data_shape}
  target:
    type:
      datasets.distribution.MGaussian1D

  batch_size: 1024
  light_weight: True
  num_workers: 16
  prefetch_factor: 4

    


model:
  method:
    type:
      rectified_flow.rectified_flow.VRF
    args:
      interp: "straight"
  net:
    type:
      models.toy_mlp.VRFNet
    args:
      data_dim: 1
      latent_dim: 2
      input_dim: 3



# model:
#   method:
#     type:
#       rectified_flow.rectified_flow.ScoringRule
#     args:
#       interp: "straight"
#   net:
#     type:
#       models.toy_mlp.VNetD
#     args:
#       data_dim: 4
#       depth: 1
#       hidden_num: 384
#       output_dim: 2


# model:
#   method:
#     type:
#       rectified_flow.rectified_flow.HRF
#     args:
#       interp: "straight"
#       depth: 2
#   net:
#     type:
#       models.toy_mlp.VNetD
#     args:
#       data_dim: 1
#       depth: 2
#       hidden_num: 128


# model:
#   method:
#     type:
#       rectified_flow.rectified_flow.GMFlow
#     args:
#       interp: "straight"
#   net:
#     type:
#       models.toy_mlp.GMFlowMLP2DDenoiser
#     args:
#       num_gaussians: 64
#       data_shape: ${data_shape}

