

data_shape: [3, 32, 32]
# [EightGaussians2D, Moon, Gaussian]
data:
  source: 
    type:
      datasets.distribution.Gaussian
    args:
      data_shape: ${data_shape}
  target:
    type:
      datasets.distribution.Cifar10

  batch_size: 4
  light_weight: False
  num_workers: 32
  prefetch_factor: 4

    


# model:
#   method:
#     type:
#       rectified_flow.rectified_flow.RectifiedFlow
#     args:
#       interp: "straight"
#   net:
#     type:
#       models.toy_mlp.VNetD
#     args:
#       data_dim: 2
#       depth: 1
#       hidden_num: 384



model:
  method:
    type:
      rectified_flow.rectified_flow.ScoringRule
    args:
      interp: "straight"
  net:
    type:
      models.unet_scoring_rule.UNetModelWrapper
    args:
      dim: ${data_shape}
      num_res_blocks: 2
      num_channels: 128
      channel_mult: [1, 2, 2, 2]
      num_heads: 4
      num_head_channels: 64
      attention_resolutions: "16"
      dropout: 0.1


# model:
#   method:
#     type:
#       rectified_flow.rectified_flow.HRF
#     args:
#       interp: "straight"
#       depth: 2
#   net:
#     type:
#       models.toy_mlp.VNetD
#     args:
#       depth: 2
#       hidden_num: 128



# model:
#   method:
#     type:
#       rectified_flow.rectified_flow.GMFlow
#     args:
#       interp: "straight"
#   net:
#     type:
#       models.toy_mlp.GMFlowMLP2DDenoiser
#     args:
#       num_gaussians: 64
#       data_shape: ${data_shape}

