

data_shape: [2]
# [EightGaussians2D, Moon, Gaussian]
data:
  source: 
    type:
      datasets.distribution.EightGaussians2D
  target:
    type:
      datasets.distribution.Moon

  batch_size: 1024
  light_weight: True
  num_workers: 8
  prefetch_factor: 4

    


# model:
#   method:
#     type:
#       rectified_flow.rectified_flow.RectifiedFlow
#     args:
#       interp: "straight"
#   net:
#     type:
#       models.toy_mlp.VNetD
#     args:
#       data_dim: 2
#       depth: 1
#       hidden_num: 384



model:
  method:
    type:
      rectified_flow.rectified_flow.ScoringRule
    args:
      interp: "straight"
  net:
    type:
      models.toy_mlp.VNetD
    args:
      data_dim: 4
      depth: 1
      hidden_num: 384
      output_dim: 2


# model:
#   method:
#     type:
#       rectified_flow.rectified_flow.HRF
#     args:
#       interp: "straight"
#       depth: 2
#   net:
#     type:
#       models.toy_mlp.VNetD
#     args:
#       depth: 2
#       hidden_num: 128



# model:
#   method:
#     type:
#       models.unet.UNetModelWrapper
#     args:
#       interp: "straight"
#   net:
#     type:
#       models.toy_mlp.GMFlowMLP2DDenoiser
#     args:
#       num_gaussians: 64